version: '3.8'
services:
  cart-1:
    build: ./cart
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
      - REDIS_HOST=storage
      - REDIS_PORT=6379
    depends_on:
      - storage
  cart-2:
    build: ./cart
    ports:
      - '4002:4002'
    environment:
      - PORT=4002
      - REDIS_HOST=storage
      - REDIS_PORT=6379
    depends_on:
      - storage
  cart-3:
    build: ./cart
    ports:
      - '4003:4003'
    environment:
      - PORT=4003
      - REDIS_HOST=storage
      - REDIS_PORT=6379
    depends_on:
      - storage
  load-balancer:
    build: ./load-balancer
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - SERVICES=cart-1:4001:15,cart-2:4002:10,cart-3:4003:5
  storage:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - storage:/data
volumes:
  storage:
    driver: local